### ISSUE TITLE
Create workflows for dApp deployment

### ISSUE THREAD

**Issue by nathanjessen** [OctoFi/octofi-app-aquafarm#91]
Use a `.github/workflows/deploy.yml` file to create a CI script for deploying the dApp when a change is made to the default repository branch.

Possible script (needs updates for our build process and branch setup)

```
name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Build dApp
        run: CI=false npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          cname: app.octo.fi
```
